### ISSUE TITLE
音频文件url可不可以做成相对路径啊！

### ISSUE THREAD

**Issue by vlalamoon** [guiqiqi/chromate#4]
**What you want [Required]**
音频文件url可不可以做成相对路径啊！

**功能描述 [必填]**
音频文件url可不可以做成相对路径啊！因为用https超链接的话还要额外部署音乐床，还要保持服务稳定，可不可以像markdown支持图片那样，把mp3放在另外一个文件夹，用绝对路径链接过去，谢谢

**The solution you think [Optional]**
Please provide a solution that you think may be possible to achieve this function, or an existing implementation (from another project).

**你认为的可能解决方案 [可选]**
请提供一个你认为不错的解决方案，或者现有从别的项目中有的实现。

**Additional context [Optional]**

**额外信息 [可选]**
这里可以填入关于此 Bug 的额外信息。

**Comment by guiqiqi** [comment]
Confirming issue

**Comment by guiqiqi** [comment]
感谢反馈。经过确认，可以使用相对路径作为音频提供源，使用方法如下：

- 在你的站点 `_config.yml` 中将选项 `post_asset_folder` 设置为 `true`
- 在生成新文章时会在 `_post` 文件夹下生成与文章同名的目录
- 将你所需要的音频放置在该目录中
- 在文章 Podcast 字段中直接填入该音频名称

这是一份示例 Podcast 配置，假定你的音频文件为 `YOUR_SOUND_TRACK.mp3`：
```
podcast:
  subtitle: A test Podcast EP
  authors: ['Doge-Gui', 'Cool Guy']
  duration: 64
  media:
    url: YOUR_SOUND_TRACK.mp3
    size: 1020453
    type: audio/mpeg
```

*额外提醒*： 这样会对原站的带宽造成较大压力，尤其是当你正在使用类似 Vercel/Netlify 之类的静态托管服务，如果你有使用类似服务的话，请咨询提供商是否允许站点分发音频之类的较大静态资源。
