### ISSUE TITLE
考虑将首页里面的 hexo-body 的高度设置为 100vh

### ISSUE THREAD

**Issue by IITII** [guiqiqi/chromate#5]
**Describe the bug [Required]**
在小屏上面打开首页确实是铺满屏幕的，但是大屏上面并不是，在最下方会有空白。
> 还是我理解错了？在大屏上首页并不需要铺满屏幕...   

> 播客详情界面，我之前用手机看的样式也是和首页一样，铺满屏幕。当初觉得很不习惯，现在改成非铺满屏幕，感觉挺好的。
> 因为这样的话会让用户觉得下面还有内容，然后下滑查看。  
> 之前那种铺满屏幕的话，如果不显示地址栏，更难受，有一种点一下回主页的感觉。  

**描述你遇到的问题 [必填]**
在这里描述你遇到问题的详细情况。
![image](https://user-images.githubusercontent.com/33705067/119587705-cee08f00-be01-11eb-81a4-beed5f6727d3.png)
![image](https://user-images.githubusercontent.com/33705067/119588319-23d0d500-be03-11eb-81b8-67e09155071c.png)

**Recurrence process [Required]**
Please describe how to reproduce this bug.
Filling in the address of the page that encountered the problem is good.

**复现过程 [必填]**
请详细描述如果复现这个问题。
有可能的话，可以贴上你遇到问题的网页地址。
[https://utc3.live/](https://utc3.live/)
**Additional context [Optional]**

**额外信息 [可选]**
这里可以填入关于此 Bug 的额外信息。

**Comment by guiqiqi** [comment]
感谢反馈。在 [这个 Commit](https://github.com/guiqiqi/chromate/commit/ef9166a92607093dea593653a9977fba40d82ad3) 中添加了设置网站 Header 部分大小的选项，具体使用方法在 `_config.yml` 文件中进行设置：

```
header:  
  index: large  # 首页 - 从大到小依次可以选择：["fullheight", "large", "medium", "default"]
  other: medium  # 其他页面 - 从大到小依次可以选择：["fullheight", "large", "medium", "default"]
  autoscroll: true
```

这样做是考虑到有些朋友不喜欢全屏幕的 Header，但是因为每个站点 Logo 大小不同的条件下，可能会出现部分 Logo 较高的站点在 **个别极小屏幕** 下选择非 `fullheight` 选项仍然出现占满首页的情况。

该功能更新将与其他一些错误修复以及新功能在下一个版本中一起发布。
