### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by PlayBoxTech** [guiqiqi/chromate#7]
**Describe the bug [Required]**
Not really a bug but more of a request for more information: In the chromate _config.yml what does the logo section do? 

**Recurrence process [Required]**
I was hoping it would allow me to put a logo on to my site, but this didn't seem to do it. 

**Additional context [Optional]**

**额外信息 [可选]**
这里可以填入关于此 Bug 的额外信息。

**Comment by guiqiqi** [comment]
Thanks for feedback.

Chromate Theme allows you to define **3 types** of your logo:
- `darkmode`: shown when the client's system is configured to dark-mode
- `lightmode`: same, but in light-mode
- `rss`: which will be used as your RSS subscription artwork

Configuration in `_config.yml`:
```
logo:
  enable: true  # Put it to true to make settings effective
  lightmode: null  # Your light-mode Logo address
  darkmode: null  # Your dark-mode Logo address
  rss: null  # RSS artwork 'Logo' address
```

Hope enjoy using Chromate.
